name: panoptic
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - backcall=0.2.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - comm=0.2.1
  - contourpy=1.2.0
  - cryptography=41.0.7
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=2.0.1
  - expat=2.5.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - intel-openmp=2021.4.0
  - ipykernel=6.29.0
  - ipython=8.12.0
  - jbig=2.1
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=2.2.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libdeflate=1.7
  - libedit=3.1.20230828
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libiconv=1.17
  - libllvm10=10.0.1
  - libopenblas=0.3.2
  - libpng=1.6.37
  - libpq=12.15
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=1.41.5
  - libuv=1.43.0
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.9
  - nettle=3.6
  - nspr=4.35
  - nss=3.89.1
  - olefile=0.47
  - openblas-devel=0.3.2
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.2.0
  - packaging=23.1
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - ply=3.11
  - plyfile=1.0.3
  - pooch=1.7.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.7
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tomli=2.0.1
  - tqdm=4.65.0
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=1.26.18
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.5
  - yacs=0.1.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - antlr4-python3-runtime==4.9.3
      - apex==0.1
      - appdirs==1.4.4
      - blinker==1.7.0
      - cityscapesscripts==2.2.2
      - click==8.1.7
      - coloredlogs==15.0.1
      - cython==3.0.8
      - einops==0.7.0
      - extension==0.0.0
      - filelock==3.13.1
      - flask==2.0.3
      - fsspec==2023.12.2
      - future==0.18.3
      - fvcore==0.1.5.post20221221
      - h5py==3.10.0
      - huggingface-hub==0.20.2
      - humanfriendly==10.0
      - imageio==2.33.1
      - install==1.3.5
      - iopath==0.1.10
      - itsdangerous==2.1.2
      - jinja2==3.1.3
      - joblib==1.3.2
      - kaolin==0.13.0
      - lazy-loader==0.3
      - markdown==3.5.2
      - markupsafe==2.1.3
      - mesh2sdf==1.1.0
      - minkowskiengine==0.5.1
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numpy==1.23.0
      - omegaconf==2.3.0
      - opencv-python==4.9.0.80
      - openexr==1.3.2
      - pillow==10.2.0
      - portalocker==2.8.2
      - pycocotools==2.0
      - pyexr==0.3.10
      - pymarchingcubes==0.0.3
      - pymcubes==0.1.4
      - pyquaternion==0.9.9
      - pysdf==0.1.9
      - pytorch3d==0.7.5
      - regex==2023.12.25
      - rtree==1.2.0
      - safetensors==0.4.1
      - scikit-image==0.22.0
      - scikit-learn==1.4.0
      - scipy==1.8.0
      - tabulate==0.9.0
      - termcolor==2.4.0
      - threadpoolctl==3.2.0
      - tifffile==2023.12.9
      - timm==0.9.12
      - tokenizers==0.15.0
      - torch==1.10.0+cu113
      - torchaudio==0.10.0+rocm4.1
      - torchvision==0.11.0+cu113
      - tornado==6.1
      - transformers==4.36.2
      - trimesh==4.0.9
      - typing==3.10.0.0
      - usd-core==22.5.post1
      - werkzeug==3.0.1
